# Generated by Django 4.2.4 on 2023-08-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='picture',
            field=models.ImageField(default='defaults/user_default.png', upload_to='images/user/picture/', verbose_name='user picture'),
        ),
    ]
