# Generated by Django 4.2.4 on 2023-08-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermodel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='About me'),
        ),
    ]
