# Generated by Django 4.2.4 on 2023-08-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermodel_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_costumer',
            field=models.BooleanField(default=True, verbose_name='Costumer status'),
        ),
    ]
