# Generated by Django 4.2.4 on 2023-08-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usermodel_is_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_signup_completed',
            field=models.BooleanField(default=False, verbose_name='Signup status'),
        ),
    ]
